{% set name = "pdoc3" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebca75b7fcf23f3b4320abe23339834d3f08c28517718e9d29e555fc38eeb33c

build:
  number: 0
  noarch: python
  entry_points:
    - pdoc = pdoc.cli:main
    - pdoc3 = pdoc.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - mako
    - markdown >=3.0
    - pip
    - python >=3.5
    - setuptools_scm
    - setuptools-git
  run:
    - mako
    - markdown >=3.0
    - python >=3.5

test:
  imports:
    - pdoc
    - pdoc.cli
    - pdoc.html_helpers

  commands:
    - pdoc --help
    - pdoc3 --help
    - python -m pdoc.test.__init__

about:
  home: https://pdoc3.github.io/pdoc/
  license: GNU Affero General Public v3 or later (AGPLv3+)
  license_family: AGPL
  license_file: LICENSE.txt
  summary: Auto-generate API documentation for Python projects.

extra:
  recipe-maintainers:
    - msarahan
